disabled: false
field_template: true
ft-default: expert
ft-show-colon: false
classes:
  region:
    - col-md-12
  field: {  }
use_field_names: true
_core:
  default_config_hash: xfB0qOeoAomOThclNNokdKTrVwXLcXz13SU3-4a5-FY
